server:
  session-timeout: 1800
  port: 8588

spring:
  mvc:
    locale: zh_CN
    locale-resolver: fixed
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jwt:
    secret: BeautifulHao
    expiration: 604800000
    tokenHeader: Authorization
  profiles:
    active: dev

#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.atom.smart.sys.entity
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: id_worker_str